package bananaLighter.hibernate.domain;

// Generated 2014-4-19 23:23:35 by Hibernate Tools 4.0.0

/**
 * CardInfo generated by hbm2java
 */
public class CardInfo implements java.io.Serializable {

	private Integer cardNo;
	private VillagerInfo villagerInfo;
	private Integer balance;

	public CardInfo() {
	}

	public CardInfo(VillagerInfo villagerInfo, Integer balance) {
		this.villagerInfo = villagerInfo;
		this.balance = balance;
	}

	public Integer getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(Integer cardNo) {
		this.cardNo = cardNo;
	}

	public VillagerInfo getVillagerInfo() {
		return this.villagerInfo;
	}

	public void setVillagerInfo(VillagerInfo villagerInfo) {
		this.villagerInfo = villagerInfo;
	}

	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

}
