package bananaLighter.hibernate.domain;

// Generated 2014-4-19 23:23:35 by Hibernate Tools 4.0.0

/**
 * CellInfo generated by hbm2java
 */
public class CellInfo implements java.io.Serializable {

	private Integer cellNo;
	private Long cellPhoneNo;
	private Float waterLevel;

	public CellInfo() {
	}

	public CellInfo(Long cellPhoneNo, Float waterLevel) {
		this.cellPhoneNo = cellPhoneNo;
		this.waterLevel = waterLevel;
	}

	public Integer getCellNo() {
		return this.cellNo;
	}

	public void setCellNo(Integer cellNo) {
		this.cellNo = cellNo;
	}

	public Long getCellPhoneNo() {
		return this.cellPhoneNo;
	}

	public void setCellPhoneNo(Long cellPhoneNo) {
		this.cellPhoneNo = cellPhoneNo;
	}

	public Float getWaterLevel() {
		return this.waterLevel;
	}

	public void setWaterLevel(Float waterLevel) {
		this.waterLevel = waterLevel;
	}

}
