package bananaLighter.hibernate.domain;

// Generated 2014-4-19 23:23:35 by Hibernate Tools 4.0.0

/**
 * CountryInfoId generated by hbm2java
 */
public class CountryInfoId implements java.io.Serializable {

	private int countryNo;
	private String countryName;

	public CountryInfoId() {
	}

	public CountryInfoId(int countryNo, String countryName) {
		this.countryNo = countryNo;
		this.countryName = countryName;
	}

	public int getCountryNo() {
		return this.countryNo;
	}

	public void setCountryNo(int countryNo) {
		this.countryNo = countryNo;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CountryInfoId))
			return false;
		CountryInfoId castOther = (CountryInfoId) other;

		return (this.getCountryNo() == castOther.getCountryNo())
				&& ((this.getCountryName() == castOther.getCountryName()) || (this
						.getCountryName() != null
						&& castOther.getCountryName() != null && this
						.getCountryName().equals(castOther.getCountryName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCountryNo();
		result = 37
				* result
				+ (getCountryName() == null ? 0 : this.getCountryName()
						.hashCode());
		return result;
	}

}
