package bananaLighter.hibernate.domain;

// Generated 2014-4-19 23:23:35 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CountryInfo generated by hbm2java
 */
public class CountryInfo implements java.io.Serializable {

	private CountryInfoId id;
	private Set<VillagerInfo> villagerInfos = new HashSet<VillagerInfo>(0);

	public CountryInfo() {
	}

	public CountryInfo(CountryInfoId id) {
		this.id = id;
	}

	public CountryInfo(CountryInfoId id, Set<VillagerInfo> villagerInfos) {
		this.id = id;
		this.villagerInfos = villagerInfos;
	}

	public CountryInfoId getId() {
		return this.id;
	}

	public void setId(CountryInfoId id) {
		this.id = id;
	}

	public Set<VillagerInfo> getVillagerInfos() {
		return this.villagerInfos;
	}

	public void setVillagerInfos(Set<VillagerInfo> villagerInfos) {
		this.villagerInfos = villagerInfos;
	}

}
