package bananaLighter.hibernate.domain;

// Generated 2014-4-19 23:23:35 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * VillagerInfo generated by hbm2java
 */
public class VillagerInfo implements java.io.Serializable {

	private VillagerInfoId id;
	private CountryInfo countryInfo;
	private String userName;
	private Set<CardInfo> cardInfos = new HashSet<CardInfo>(0);

	public VillagerInfo() {
	}

	public VillagerInfo(VillagerInfoId id, CountryInfo countryInfo,
			String userName) {
		this.id = id;
		this.countryInfo = countryInfo;
		this.userName = userName;
	}

	public VillagerInfo(VillagerInfoId id, CountryInfo countryInfo,
			String userName, Set<CardInfo> cardInfos) {
		this.id = id;
		this.countryInfo = countryInfo;
		this.userName = userName;
		this.cardInfos = cardInfos;
	}

	public VillagerInfoId getId() {
		return this.id;
	}

	public void setId(VillagerInfoId id) {
		this.id = id;
	}

	public CountryInfo getCountryInfo() {
		return this.countryInfo;
	}

	public void setCountryInfo(CountryInfo countryInfo) {
		this.countryInfo = countryInfo;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Set<CardInfo> getCardInfos() {
		return this.cardInfos;
	}

	public void setCardInfos(Set<CardInfo> cardInfos) {
		this.cardInfos = cardInfos;
	}

}
