package bananaLighter.hibernate.domain;

// Generated 2014-4-19 23:23:35 by Hibernate Tools 4.0.0

/**
 * VillagerInfoId generated by hbm2java
 */
public class VillagerInfoId implements java.io.Serializable {

	private int userNo;
	private String countryName;

	public VillagerInfoId() {
	}

	public VillagerInfoId(int userNo, String countryName) {
		this.userNo = userNo;
		this.countryName = countryName;
	}

	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VillagerInfoId))
			return false;
		VillagerInfoId castOther = (VillagerInfoId) other;

		return (this.getUserNo() == castOther.getUserNo())
				&& ((this.getCountryName() == castOther.getCountryName()) || (this
						.getCountryName() != null
						&& castOther.getCountryName() != null && this
						.getCountryName().equals(castOther.getCountryName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserNo();
		result = 37
				* result
				+ (getCountryName() == null ? 0 : this.getCountryName()
						.hashCode());
		return result;
	}

}
